### ISSUE TITLE
5.0.4 raises TypeError

### ISSUE THREAD

**Issue by alphachai** [timothycrosley/isort#1288]
All of my builds that run the latest isort are failing this morning. I'm using no additional config in this example.

```
> $ isort --check-only ./example.py
Traceback (most recent call last):
  File "[path]/bin/isort", line 10, in <module>
    sys.exit(main())
  File "[path]/lib/python3.8/site-packages/isort/main.py", line 688, in main
    config = Config(**config_dict)
  File "[path]/lib/python3.8/site-packages/isort/settings.py", line 309, in __init__
    super().__init__(sources=tuple(sources), **combined_config)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'not_skip'
```

I have yet to find a way to run isort 5.0.4 without raising this exception.

**Comment by alphachai** [comment]
I just discovered one of the failing projects IS using additional config, and that may be source of all these issues. Investigating further...

**Comment by alphachai** [comment]
Removing `not_skip` from the isort config found in one of the offending project's dotfiles seems to have fixed this. It feels strange to suddenly break on a setting that isn't recognized, even if it was cargo-culted to this project from some legacy version of isort.
